### ISSUE TITLE
laminar.iter_flow tests -- return order of results dictionary keys.

### ISSUE THREAD

**Issue by kmayerb** [dgellerup/laminar#1]
I love this package! Thanks for all the work developing it thus far.

I added some [basic](https://github.com/kmayerb/laminar/blob/staging/test/test_iter_flow.py)  and more [complex tests ](https://github.com/kmayerb/laminar/blob/a0489b520abc9d82de51b9dd5aabb4dd527c21fd/test/test_iter_flow_complex.py)  of iter_flow() on a [ forked repo ](https://github.com/kmayerb/laminar/tree/staging)

![Screen Shot 2019-11-11 at 5 41 02 PM](https://user-images.githubusercontent.com/46639063/68634474-77423300-04aa-11ea-9808-99ea8f7c668d.png)

![Screen Shot 2019-11-11 at 5 31 54 PM](https://user-images.githubusercontent.com/46639063/68634099-2bdb5500-04a9-11ea-9742-43ef021f00d9.png)

1. Running them, one of the things I noticed is that varying the number of cores and the length of the iterable could cause the tests to fail which had otherwised passed. It seems that cause of the failures is the order in which the returned results dictionary returns keys. It does not always return in matching order to the iterable. This can make it hard to reassemble the results if order matters as it does in the tests, written.

I was running in  Python 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46) 
```
pytest test/test_iterflow_complex.py -v
```

```
>>>  [print(k) for k in r.keys()]
-------------------------------------------- Captured stdout call --------------------------------------------
data[160-319]
data[0-159] ## <<-------------- **out of order**
data[320-479]
data[480-638]
data[639-797]
data[798-956]
data[957-1115]
data[1116-1274]
_________________
```

2. In another test I explored whether I could increase the length of tuples being iterated through. At n = 66 (which creates tuple for all coordinates in an upper triangular 66x66 matrix), using cores = 2), iter_flow hangs on my machine, even thought it was perfectly happy with n = 65. I am going to look into this further tomorrow, but you might want to run these tests and see if you have similar issues. It may point to a hidden issue. 

Thanks,
kmayerb

**Comment by dgellerup** [comment]
Hey Koshlan,

Thanks for checking this project out and sending feedback! The results dict implementation as it currently stands has it returning in the order that the processes finish. I did this on purpose as a design choice since I was working from a mindset where the end user is solely responsible for recompilation. It's a trade off of convenience and speed, since sorting results takes more time (however little), and not all use cases need the data to be sorted. But, I think you have a good point! I will add a keyword arg that a user can set to True that will sort output.

As for the issue with laminar hanging, I forgot to mention during the presentation that for a couple functions I had to really be cognizant of memory usage. I would get hung processes even with valid code, and realized that the computations were guzzling RAM, causing the processes to freeze. I was able to rearrange my function to allow Python to collect garbage, and threw a few del statements in there as well, and it cleared up the issue. Not saying that that's your issue, but I think it's good to keep in mind. I will try these tests out on my machine to see if I get the same behavior that you're experiencing, and if so maybe we can put our heads together to figure out what's going on.

Again, thanks for the feedback!

- Dane

**Comment by kmayerb** [comment]
The first issue seems to be solved easily. I submitted a Pull Request for reference and including the tests. Please feel free to ignore and implement your preferred syntax.

Let me know once you try to replicate the second issue, by increasing n to something larger than 65 in the test below. I would be surprised if it was a memory issue given how small the input matrix is. 

```
def test_using_laminar_iterflow(n, cores):
    """ Test the process in parrallel (no iter.flow)"""
    # Here is the process in series
    mat = np.random.rand(n,5)
    ijs = get_pwdist_indices(np.arange(n))
    distances = vectorize_tuple_to_dist(ijs, matrix = mat, func = cosine_dist)
    assert(len(distances) == len(ijs))

    r = laminar.iter_flow(function = vectorize_tuple_to_dist,
                      data = ijs,
                      matrix = mat,
                      func = cosine_dist,
                      cores= cores,
                      sort_results = True)
    [print(k) for k in r.keys()]
    assert np.allclose(collapse(r), distances, atol=1e-3)

```

**Comment by dgellerup** [comment]
So I've been playing around with this test and have had no luck in fixing it. I've found it also hangs on (66, 3). It's not successfully joining the final process in the `for p in processes: p.join()` call. Have you investigated any further on your end? I'll keep searching for answers for now

**Comment by dgellerup** [comment]
Hey Koshlan,

I've finally returned to this and fixed the issue. I was able to run your complex tests locally and they all passed. The fix involved de-queueing results from the Queue() object as they finish. Multiprocessing Queue objects have a max size, and we were seeing things hang when there was too much data being added to the Queue. Processes are joined afterwards.
